engines:
  rubocop:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - card/lib/**
   - card/mod/**
   - wagn/lib/**
   - wagn/rails/**
   - "**.rb"
exclude_paths:
- wagn/rails/assets/**/*
- card/mod/03_machines/lib/javascript/**/*
- card/mod/06_bootstrap/lib/javascript/**/*
- card/spec/**/*
- wagn/spec/**/*
